function skillsMember() {
    return [
        "Javascript",
        "Node.js",
        "React",
        "MongoDB",
        "Express",
        "Firebase",
        "Git",
        "HTML",
        "CSS",
        "SASS",
        "Bootstrap",
        "Material UI",
        "Jest",
        "Cypress",
        "Mocha",
        "Chai",
        "Heroku",
        "Netlify",
        "AWS",
        "Azure",
        "Google Cloud",
        "Docker",
        "Kubernetes",
        "Jenkins",
        "Travis CI",
        "Circle CI",
        "GitLab CI",
        "Trello",
        "Jira",
        "Slack",
        "Microsoft Teams",
        "Discord",
        "Zoom",
        "Google Meet",
        "Webex",
        "Skype",
        "Hangouts",
        "Outlook",
        "Gmail",
        "Google Calendar",
        "iCal",
        "Outlook Calendar",
        "Google Drive",
        "Dropbox",
        "OneDrive",
        "Slack Drive",
        "Microsoft Teams Drive",
        "Google Docs",
        "Google Sheets",
        "Google Slides",
        "Google Forms",
        "Google Sites",
        "Google Meet",
        "Google Chat",
        "Google Keep",
        "Google Tasks",
        "Google Calendar",
        "Google Cloud Platform",
        "Google Cloud Console",
        "Google Cloud Functions",
        "Google Cloud Storage",
        "Google Cloud SQL",
        "Google Cloud Firestore",
        "Google Cloud BigQuery",
        "Google Cloud Pub/Sub",
        "Google Cloud IAM",
        "Google Cloud CDN",
        "Google Cloud VPN",
        "Google Cloud DNS",
        "Google Cloud Load Balancer",
        "Google Cloud CDN",
        "Google Cloud Functions",
        "Google Cloud Storage",
        "Google Cloud SQL",
        "Google Cloud Firestore",
        "Google Cloud BigQuery",
        "Google Cloud Pub/Sub",
        "Google Cloud IAM",
        "Google Cloud CDN",
        "Google Cloud VPN",
        "Google Cloud DNS",
        "Google Cloud Load Balancer",
        "Google Cloud CDN",
        "Google Cloud Functions",
        "Google Cloud Storage",
        "Google Cloud SQL",
        "Google Cloud Firestore",
        "Google Cloud BigQuery",
        "Google Cloud Pub/Sub",
        "Google Cloud IAM",
        "Google Cloud CDN"]}